import { nanoid } from 'nanoid'
import { EquipmentTypes, type LabelAndEquipmentProps } from './listCheckerProps'

export const SECTION_IDS = {
  AUDIO_SYSTEM: nanoid(),
  LIGHTING_SYSTEM: nanoid(),
  MICROPHONE: nanoid(),
  DRUMS: nanoid(),
  AMPLIFIERS: nanoid(),
  OTHERS: nanoid(),
  CREW_AND_TRANSPORT: nanoid(),
  ADD_ONS: nanoid(),
  LED_WALL: nanoid(),
  OFFICIAL_RECEIPT_FEE: nanoid(),
  TRANSPORTATION_FEE: nanoid(),
  LED_WALL_RISER: nanoid(),
} as const

export const ITEM_IDS = {
  AUDIO_SPEAKERS_2: nanoid(),
  AUDIO_SPEAKERS_2_DUP: nanoid(),
  AUDIO_SPEAKERS_2_YAMAHA_DZR15: nanoid(),
  AUDIO_SPEAKERS_2_RCF_935: nanoid(),
  AUDIO_MIXER_SQ5: nanoid(),
  AUDIO_SUBWOOFERS_2_KW181: nanoid(),
  AUDIO_MONITOR_SPEAKERS_2_QSC_K12: nanoid(),
  AUDIO_MONITOR_SPEAKERS_4_QSC_YAMAHA: nanoid(),
  AUDIO_STAGE_BOX_AR2412: nanoid(),
  AUDIO_SUB_2_KLA181: nanoid(),
  AUDIO_DELAY_SPEAKERS_2_RCF_915: nanoid(),
  AUDIO_FRONTFILL_SPEAKERS_2_YAMAHA_DXR10: nanoid(),
  AUDIO_SUBWOOFERS_4_KLA181: nanoid(),
  LIGHT_BACKLIGHTS_RGB_4: nanoid(),
  LIGHT_BACKLIGHTS_RGB_8: nanoid(),
  LIGHT_DMX_512_CONTROLLER: nanoid(),
  LIGHT_CONTROLLER_MINIPEARL_1024: nanoid(),
  LIGHT_FRONT_LIGHTS_AMBER_4: nanoid(),
  LIGHT_FRONT_LIGHTS_AMBER_8: nanoid(),
  ACCESSORY_T_BAR_STANDS_2: nanoid(),
  ACCESSORY_T_BAR_STANDS_4: nanoid(),
  LIGHT_MOVING_HEADLIGHTS_2: nanoid(),
  LIGHT_MOVING_HEADLIGHTS_2_MORE: nanoid(),
  LIGHT_MOVING_HEADS_SET_4_WITH_TRUSSES: nanoid(),
  LIGHT_MOVING_WASH_2: nanoid(),
  LIGHT_PAR_LIGHTS_16: nanoid(),
  LIGHT_FRONTAL_LIGHTS_8: nanoid(),
  EFFECT_HAZE_MACHINE: nanoid(),
  LIGHT_BACKDROP_LIGHTS_16: nanoid(),
  MIC_WIRELESS_2: nanoid(),
  MIC_WIRED_1: nanoid(),
  MIC_WIRED_2: nanoid(),
  MIC_WIRED_5: nanoid(),
  MIC_WIRELESS_4: nanoid(),
  MIC_WIRELESS_7: nanoid(),
  DRUMS_DRUMSET: nanoid(),
  DRUMS_CYMBALS: nanoid(),
  DRUMS_KICK_PEDAL: nanoid(),
  DRUMS_KICK_MIC: nanoid(),
  DRUMS_SNARE_MIC: nanoid(),
  DRUMS_TOM_MICS_2: nanoid(),
  DRUMS_OVERHEAD_MIC_1: nanoid(),
  AMP_GUITAR_AMPLIFIERS_2: nanoid(),
  AMP_BASS_AMPLIFIER: nanoid(),
  AMP_GUITAR_MICS_2: nanoid(),
  OTHER_SPEAKER_STANDS_2: nanoid(),
  OTHER_XLR_CABLES: nanoid(),
  OTHER_CABLE_RAMPS_2: nanoid(),
  OTHER_EXTENSION_CABLES: nanoid(),
  OTHER_AUX_CABLE: nanoid(),
  OTHER_MIC_STAND_1: nanoid(),
  OTHER_MIC_STANDS_3: nanoid(),
  OTHER_LYRIC_STAND_1: nanoid(),
  OTHER_FOG_MACHINE_1: nanoid(),
  OTHER_COMM_SET_6: nanoid(),
  OTHER_LED_WALL_9X12: nanoid(),
  OTHER_LED_WALL_9X14: nanoid(),
  OTHER_STAGE_16X24: nanoid(),
  CREW_TECH_2: nanoid(),
  CREW_TECH_3: nanoid(),
  CREW_TECH_4: nanoid(),
  CREW_TRANSPORT_SERVICE: nanoid(),
  CREW_TECH_5: nanoid(),
  ADDON_QSC_SUBWOOFERS_2: nanoid(),
  ADDON_QSC_MONITOR_SPEAKERS_2: nanoid(),
  ADDON_MOVING_HEADLIGHTS_2: nanoid(),
  ADDON_MOVING_HEADLIGHTS_2_MORE: nanoid(),
  ADDON_YAMAHA_MONITORS_2: nanoid(),
  LED_WALL_9X12: nanoid(),
  LED_WALL_9X14: nanoid(),
  FEE_OR: nanoid(),
  FEE_TRANSPO: nanoid(),
  FEE_RISER: nanoid(),
} as const

export const SAMPLE_OBJECT_ARRAY: LabelAndEquipmentProps[] = [
  {
    id: SECTION_IDS.AUDIO_SYSTEM,
    label: 'Audio System',
    equipment: [
      {
        id: ITEM_IDS.AUDIO_SPEAKERS_2,
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 Powered Speakers - RCF ART 745A MK4',
      },
      {
        id: ITEM_IDS.AUDIO_SPEAKERS_2_DUP,
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 Powered Speakers - RCF ART 745A MK4',
      },
      {
        id: ITEM_IDS.AUDIO_SPEAKERS_2_YAMAHA_DZR15,
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 Powered Speakers - Yamaha DZR15',
      },
      {
        id: ITEM_IDS.AUDIO_SPEAKERS_2_RCF_935,
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 Powered Speakers - RCF 935',
      },
      {
        id: ITEM_IDS.AUDIO_MIXER_SQ5,
        isChecked: false,
        type: EquipmentTypes.MIXER,
        name: '1 Digital Mixer - Allen & Heath SQ5',
      },
      {
        id: ITEM_IDS.AUDIO_SUBWOOFERS_2_KW181,
        isChecked: false,
        type: EquipmentTypes.SUBWOOFER,
        name: '2 Subwoofers - QSC KW181',
      },
      {
        id: ITEM_IDS.AUDIO_MONITOR_SPEAKERS_2_QSC_K12,
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 Monitor Speakers - QSC K12',
      },
      {
        id: ITEM_IDS.AUDIO_MONITOR_SPEAKERS_4_QSC_YAMAHA,
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '4 Monitor Speakers - QSC K12 & Yamaha DXR10',
      },
      {
        id: ITEM_IDS.AUDIO_STAGE_BOX_AR2412,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '1 Digital Stage Box - Allen & Heath AR2412',
      },
      {
        id: ITEM_IDS.AUDIO_SUB_2_KLA181,
        isChecked: false,
        type: EquipmentTypes.SUBWOOFER,
        name: '2 Subwoofers - QSC KLA181',
      },
      {
        id: ITEM_IDS.AUDIO_DELAY_SPEAKERS_2_RCF_915,
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 Delay Speakers - RCF 915',
      },
      {
        id: ITEM_IDS.AUDIO_FRONTFILL_SPEAKERS_2_YAMAHA_DXR10,
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 Frontfill Speakers - Yamaha DXR10',
      },
      {
        id: ITEM_IDS.AUDIO_SUBWOOFERS_4_KLA181,
        isChecked: false,
        type: EquipmentTypes.SUBWOOFER,
        name: '4 Subwoofers - QSC KLA181',
      },
    ],
  },
  {
    id: SECTION_IDS.LIGHTING_SYSTEM,
    label: 'Lighting System',
    equipment: [
      {
        id: ITEM_IDS.LIGHT_BACKLIGHTS_RGB_4,
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '4 Par RGB Backlights',
      },
      {
        id: ITEM_IDS.LIGHT_BACKLIGHTS_RGB_8,
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '8 Par RGB Backlights',
      },
      {
        id: ITEM_IDS.LIGHT_DMX_512_CONTROLLER,
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '1 DMX 512 Controller - DMX 512',
      },
      {
        id: ITEM_IDS.LIGHT_CONTROLLER_MINIPEARL_1024,
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '1 Light Controller - Minipearl 1024',
      },
      {
        id: ITEM_IDS.LIGHT_FRONT_LIGHTS_AMBER_4,
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '4 Amber Front Lights',
      },
      {
        id: ITEM_IDS.LIGHT_FRONT_LIGHTS_AMBER_8,
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '8 Amber Front Lights',
      },
      {
        id: ITEM_IDS.ACCESSORY_T_BAR_STANDS_2,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '2 T-Bar Stands - Holds Par Lights',
      },
      {
        id: ITEM_IDS.ACCESSORY_T_BAR_STANDS_4,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '4 T-Bar Stands - Holds Par Lights',
      },
      {
        id: ITEM_IDS.LIGHT_MOVING_HEADLIGHTS_2,
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '2 Moving Headlights - Beam 295',
      },
      {
        id: ITEM_IDS.LIGHT_MOVING_HEADLIGHTS_2_MORE,
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '2 More Moving Headlights - Beam 295 (+P2,000)',
      },
      {
        id: ITEM_IDS.LIGHT_MOVING_HEADS_SET_4_WITH_TRUSSES,
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '4 Moving Heads Set - Beam 295 w/ Trusses',
      },
      {
        id: ITEM_IDS.LIGHT_MOVING_WASH_2,
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '2 Moving Wash - 19x15WATT LED',
      },
      {
        id: ITEM_IDS.LIGHT_PAR_LIGHTS_16,
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '16 PCS Par Lights - RGB Par Lights',
      },
      {
        id: ITEM_IDS.LIGHT_FRONTAL_LIGHTS_8,
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '8 Frontal Lights - Amber White Par Lights',
      },
      {
        id: ITEM_IDS.EFFECT_HAZE_MACHINE,
        isChecked: false,
        type: EquipmentTypes.EFFECT,
        name: 'Haze Machine - For Stage Haze',
      },
      {
        id: ITEM_IDS.LIGHT_BACKDROP_LIGHTS_16,
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '16 PCS Back Drop Lights - RGB Par Lights',
      },
    ],
  },
  {
    id: SECTION_IDS.MICROPHONE,
    label: 'Microphone',
    equipment: [
      {
        id: ITEM_IDS.MIC_WIRELESS_2,
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '2 Wireless Mics - Mipro 311B',
      },
      {
        id: ITEM_IDS.MIC_WIRED_1,
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '1 Wired Mic - Sennheiser E935',
      },
      {
        id: ITEM_IDS.MIC_WIRED_2,
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '2 Wired Mics - Sennheiser E935',
      },
      {
        id: ITEM_IDS.MIC_WIRED_5,
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '5 Wired Mics',
      },
      {
        id: ITEM_IDS.MIC_WIRELESS_4,
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '4 Wireless Mics - Mipro 311B',
      },
      {
        id: ITEM_IDS.MIC_WIRELESS_7,
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '7 Wireless Mics - Mipro 311B',
      },
    ],
  },
  {
    id: SECTION_IDS.DRUMS,
    label: 'Drums',
    equipment: [
      {
        id: ITEM_IDS.DRUMS_DRUMSET,
        isChecked: false,
        type: EquipmentTypes.INSTRUMENT,
        name: 'Drumset - Pearl Export',
      },
      {
        id: ITEM_IDS.DRUMS_CYMBALS,
        isChecked: false,
        type: EquipmentTypes.INSTRUMENT,
        name: 'Cymbals - Sabian HHX & AAX',
      },
      {
        id: ITEM_IDS.DRUMS_KICK_PEDAL,
        isChecked: false,
        type: EquipmentTypes.INSTRUMENT,
        name: 'Kick Pedal - Iron Cobra 600',
      },
      {
        id: ITEM_IDS.DRUMS_KICK_MIC,
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: 'Kick Mic - Shure Beta 52A',
      },
      {
        id: ITEM_IDS.DRUMS_SNARE_MIC,
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: 'Snare Mic - Shure SM57',
      },
      {
        id: ITEM_IDS.DRUMS_TOM_MICS_2,
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '2 Tom Mics - Shure PGA 56',
      },
      {
        id: ITEM_IDS.DRUMS_OVERHEAD_MIC_1,
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '1 Overhead Mic - Shure PGA 81',
      },
    ],
  },
  {
    id: SECTION_IDS.AMPLIFIERS,
    label: 'Amplifiers',
    equipment: [
      {
        id: ITEM_IDS.AMP_GUITAR_AMPLIFIERS_2,
        isChecked: false,
        type: EquipmentTypes.AMPLIFIER,
        name: '2 Guitar Amplifiers - Laney LX120R Twin',
      },
      {
        id: ITEM_IDS.AMP_BASS_AMPLIFIER,
        isChecked: false,
        type: EquipmentTypes.AMPLIFIER,
        name: 'Bass Amplifier - GK MB115',
      },
      {
        id: ITEM_IDS.AMP_GUITAR_MICS_2,
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '2 Guitar Mics - Shure SM56',
      },
    ],
  },
  {
    id: SECTION_IDS.OTHERS,
    label: 'Others',
    equipment: [
      {
        id: ITEM_IDS.OTHER_SPEAKER_STANDS_2,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '2 Speaker Stands - Height Adjustable Stands',
      },
      {
        id: ITEM_IDS.OTHER_XLR_CABLES,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: 'XLR Cables - Enough Cables for Event',
      },
      {
        id: ITEM_IDS.OTHER_CABLE_RAMPS_2,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '2 Cable Ramps - Solid Quality Ramps',
      },
      {
        id: ITEM_IDS.OTHER_EXTENSION_CABLES,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: 'Extension Cables - High Quality Extension Cables',
      },
      {
        id: ITEM_IDS.OTHER_AUX_CABLE,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '3.5mm Aux Cable - Play Your Music for Event',
      },
      {
        id: ITEM_IDS.OTHER_MIC_STAND_1,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '1 Mic Stand - With Press to Adjust',
      },
      {
        id: ITEM_IDS.OTHER_MIC_STANDS_3,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '3 Mic Stands - With Press to Adjust',
      },
      {
        id: ITEM_IDS.OTHER_LYRIC_STAND_1,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '1 Lyric Stand - Add Upon Request',
      },
      {
        id: ITEM_IDS.OTHER_FOG_MACHINE_1,
        isChecked: false,
        type: EquipmentTypes.EFFECT,
        name: '1 Fog Machine - Titanium Audio',
      },
      {
        id: ITEM_IDS.OTHER_COMM_SET_6,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '6 Comm-Set - Event Communication',
      },
      {
        id: ITEM_IDS.OTHER_LED_WALL_9X12,
        isChecked: false,
        type: EquipmentTypes.LED_WALL,
        name: '9x12 FT LED Wall - 7680 Refresh Rate, 1K NITS',
      },
      {
        id: ITEM_IDS.OTHER_LED_WALL_9X14,
        isChecked: false,
        type: EquipmentTypes.LED_WALL,
        name: '9x14 FT LED Wall - 7680 Refresh Rate, 1K NITS',
      },
      {
        id: ITEM_IDS.OTHER_STAGE_16X24,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '16x24 FT Stage - Aluminum Stage w/ Stairs',
      },
    ],
  },
  {
    id: SECTION_IDS.CREW_AND_TRANSPORT,
    label: 'Crew and Transport',
    equipment: [
      {
        id: ITEM_IDS.CREW_TECH_2,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '2 Tech Crews - Experts from Legato',
      },
      {
        id: ITEM_IDS.CREW_TECH_3,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '3 Tech Crews - Experts from Legato',
      },
      {
        id: ITEM_IDS.CREW_TECH_4,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '4 Tech Crews - Experts from Legato',
      },
      {
        id: ITEM_IDS.CREW_TRANSPORT_SERVICE,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: 'Transport Service - Mitsubishi L300',
      },
      {
        id: ITEM_IDS.CREW_TECH_5,
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '5 Tech Crews - Experts from Legato',
      },
    ],
  },
  {
    id: SECTION_IDS.ADD_ONS,
    label: 'Add-ons',
    equipment: [
      {
        id: ITEM_IDS.ADDON_QSC_SUBWOOFERS_2,
        isChecked: false,
        type: EquipmentTypes.SUBWOOFER,
        name: '2 QSC Subwoofers (+P3,000)',
      },
      {
        id: ITEM_IDS.ADDON_QSC_MONITOR_SPEAKERS_2,
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 QSC Monitor Speakers (+P2,000)',
      },
      {
        id: ITEM_IDS.ADDON_MOVING_HEADLIGHTS_2,
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '2 Moving Headlights (+P2,000)',
      },
      {
        id: ITEM_IDS.ADDON_MOVING_HEADLIGHTS_2_MORE,
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '2 More Moving Headlights (+P2,000)',
      },
      {
        id: ITEM_IDS.ADDON_YAMAHA_MONITORS_2,
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 Yamaha Monitors (+P2,000)',
      },
    ],
  },
  {
    id: SECTION_IDS.LED_WALL,
    label: 'LED Wall',
    singleSelect: true,
    equipment: [
      {
        id: ITEM_IDS.LED_WALL_9X12,
        isChecked: false,
        type: EquipmentTypes.LED_WALL,
        name: '9x12 ft LED Wall',
      },
      {
        id: ITEM_IDS.LED_WALL_9X14,
        isChecked: false,
        type: EquipmentTypes.LED_WALL,
        name: '9x14 ft LED Wall',
      },
    ],
  },
  {
    id: SECTION_IDS.OFFICIAL_RECEIPT_FEE,
    label: 'Official Receipt Fee',
    equipment: [
      {
        id: ITEM_IDS.FEE_OR,
        isChecked: false,
        type: EquipmentTypes.FEE,
        name: 'OR Fee',
      },
    ],
  },
  {
    id: SECTION_IDS.TRANSPORTATION_FEE,
    label: 'Transportation Fee',
    equipment: [
      {
        id: ITEM_IDS.FEE_TRANSPO,
        isChecked: false,
        type: EquipmentTypes.FEE,
        name: 'Transpo Fee',
      },
    ],
  },
  {
    id: SECTION_IDS.LED_WALL_RISER,
    label: 'LED Wall Riser',
    equipment: [
      {
        id: ITEM_IDS.FEE_RISER,
        isChecked: false,
        type: EquipmentTypes.FEE,
        name: 'Riser',
      },
    ],
  },
]
