import { nanoid } from 'nanoid'
import { EquipmentTypes, type LabelAndEquipmentProps } from './listCheckerProps'

export const SECTION_IDS = {
  AUDIO_SYSTEM: nanoid(),
  LIGHTING_SYSTEM: nanoid(),
  MICROPHONE: nanoid(),
  DRUMS: nanoid(),
  AMPLIFIERS: nanoid(),
  OTHERS: nanoid(),
  CREW_AND_TRANSPORT: nanoid(),
  ADD_ONS: nanoid(),
  LED_WALL: nanoid(),
  OFFICIAL_RECEIPT_FEE: nanoid(),
  TRANSPORTATION_FEE: nanoid(),
  LED_WALL_RISER: nanoid(),
} as const

export const SAMPLE_OBJECT_ARRAY: LabelAndEquipmentProps[] = [
  {
    id: SECTION_IDS.AUDIO_SYSTEM,
    label: 'Audio System',
    equipment: [
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 Powered Speakers - RCF ART 745A MK4',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 Powered Speakers - RCF ART 745A MK4',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 Powered Speakers - Yamaha DZR15',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 Powered Speakers - RCF 935',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.MIXER,
        name: '1 Digital Mixer - Allen & Heath SQ5',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.SUBWOOFER,
        name: '2 Subwoofers - QSC KW181',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 Monitor Speakers - QSC K12',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '4 Monitor Speakers - QSC K12 & Yamaha DXR10',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '1 Digital Stage Box - Allen & Heath AR2412',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.SUBWOOFER,
        name: '2 Subwoofers - QSC KLA181',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 Delay Speakers - RCF 915',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 Frontfill Speakers - Yamaha DXR10',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.SUBWOOFER,
        name: '4 Subwoofers - QSC KLA181',
      },
    ],
  },
  {
    id: SECTION_IDS.LIGHTING_SYSTEM,
    label: 'Lighting System',
    equipment: [
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '4 Par RGB Backlights',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '8 Par RGB Backlights',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '1 DMX 512 Controller - DMX 512',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '1 Light Controller - Minipearl 1024',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '4 Amber Front Lights',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '8 Amber Front Lights',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '2 T-Bar Stands - Holds Par Lights',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '4 T-Bar Stands - Holds Par Lights',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '2 Moving Headlights - Beam 295',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '2 More Moving Headlights - Beam 295 (+P2,000)',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '4 Moving Heads Set - Beam 295 w/ Trusses',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '2 Moving Wash - 19x15WATT LED',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '16 PCS Par Lights - RGB Par Lights',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '8 Frontal Lights - Amber White Par Lights',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.EFFECT,
        name: 'Haze Machine - For Stage Haze',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '16 PCS Back Drop Lights - RGB Par Lights',
      },
    ],
  },
  {
    id: SECTION_IDS.MICROPHONE,
    label: 'Microphone',
    equipment: [
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '2 Wireless Mics - Mipro 311B',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '1 Wired Mic - Sennheiser E935',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '2 Wired Mics - Sennheiser E935',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '5 Wired Mics',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '4 Wireless Mics - Mipro 311B',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '7 Wireless Mics - Mipro 311B',
      },
    ],
  },
  {
    id: SECTION_IDS.DRUMS,
    label: 'Drums',
    equipment: [
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.INSTRUMENT,
        name: 'Drumset - Pearl Export',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.INSTRUMENT,
        name: 'Cymbals - Sabian HHX & AAX',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.INSTRUMENT,
        name: 'Kick Pedal - Iron Cobra 600',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: 'Kick Mic - Shure Beta 52A',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: 'Snare Mic - Shure SM57',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '2 Tom Mics - Shure PGA 56',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '1 Overhead Mic - Shure PGA 81',
      },
    ],
  },
  {
    id: SECTION_IDS.AMPLIFIERS,
    label: 'Amplifiers',
    equipment: [
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.AMPLIFIER,
        name: '2 Guitar Amplifiers - Laney LX120R Twin',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.AMPLIFIER,
        name: 'Bass Amplifier - GK MB115',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.MICROPHONE,
        name: '2 Guitar Mics - Shure SM56',
      },
    ],
  },
  {
    id: SECTION_IDS.OTHERS,
    label: 'Others',
    equipment: [
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '2 Speaker Stands - Height Adjustable Stands',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: 'XLR Cables - Enough Cables for Event',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '2 Cable Ramps - Solid Quality Ramps',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: 'Extension Cables - High Quality Extension Cables',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '3.5mm Aux Cable - Play Your Music for Event',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '1 Mic Stand - With Press to Adjust',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '3 Mic Stands - With Press to Adjust',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '1 Lyric Stand - Add Upon Request',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.EFFECT,
        name: '1 Fog Machine - Titanium Audio',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '6 Comm-Set - Event Communication',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LED_WALL,
        name: '9x12 FT LED Wall - 7680 Refresh Rate, 1K NITS',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LED_WALL,
        name: '9x14 FT LED Wall - 7680 Refresh Rate, 1K NITS',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '16x24 FT Stage - Aluminum Stage w/ Stairs',
      },
    ],
  },
  {
    id: SECTION_IDS.CREW_AND_TRANSPORT,
    label: 'Crew and Transport',
    equipment: [
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '2 Tech Crews - Experts from Legato',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '3 Tech Crews - Experts from Legato',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '4 Tech Crews - Experts from Legato',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: 'Transport Service - Mitsubishi L300',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.ACCESSORY,
        name: '5 Tech Crews - Experts from Legato',
      },
    ],
  },
  {
    id: SECTION_IDS.ADD_ONS,
    label: 'Add-ons',
    equipment: [
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.SUBWOOFER,
        name: '2 QSC Subwoofers (+P3,000)',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 QSC Monitor Speakers (+P2,000)',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '2 Moving Headlights (+P2,000)',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LIGHT,
        name: '2 More Moving Headlights (+P2,000)',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.SPEAKER,
        name: '2 Yamaha Monitors (+P2,000)',
      },
    ],
  },
  {
    id: SECTION_IDS.LED_WALL,
    label: 'LED Wall',
    singleSelect: true,
    equipment: [
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LED_WALL,
        name: '9x12 ft LED Wall',
      },
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.LED_WALL,
        name: '9x14 ft LED Wall',
      },
    ],
  },
  {
    id: SECTION_IDS.OFFICIAL_RECEIPT_FEE,
    label: 'Official Receipt Fee',
    equipment: [
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.FEE,
        name: 'OR Fee',
      },
    ],
  },
  {
    id: SECTION_IDS.TRANSPORTATION_FEE,
    label: 'Transportation Fee',
    equipment: [
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.FEE,
        name: 'Transpo Fee',
      },
    ],
  },
  {
    id: SECTION_IDS.LED_WALL_RISER,
    label: 'LED Wall Riser',
    equipment: [
      {
        id: nanoid(),
        isChecked: false,
        type: EquipmentTypes.FEE,
        name: 'Riser',
      },
    ],
  },
]
